name: Elastic Beanstalk Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install Elastic Beanstalk CLI
        run: |
          pip install awsebcli --upgrade --user

      - name: Configure AWS credentials
        run: |
          mkdir -p ~/.aws/
          echo "[default]" > ~/.aws/config
          echo "region=${{ env.AWS_REGION }}" >> ~/.aws/config
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ env.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Create Elastic Beanstalk Application
        run: |
          eb init -p "Corretto 8" -i "64bit Amazon Linux 2 v3.4.7" --region ${{ env.AWS_REGION }} ${{ env.AWS_ELASTIC_BEANSTALK_APPLICATION_NAME }} 
          eb create ${{ env.AWS_ELASTIC_BEANSTALK_ENVIRONMENT_NAME }} --single --region ${{ env.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        run: |
          mvn clean package
          aws s3 cp target/spring-app.war s3://${{ env.AWS_ELASTIC_BEANSTALK_S3_BUCKET }}/
          eb deploy --region ${{ env.AWS_REGION }} --version-label ${{ github.sha }} --staged

      - name: Show Elastic Beanstalk Environment URL
        run: |
          eb status --region ${{ env.AWS_REGION }}
